add_requires("gtest")
set_languages("c++20")
add_rules("mode.release")

target("exif4cpp")
    set_kind("static")
    set_symbols("debug")
    add_files("src/*.cpp")
    add_headerfiles("src/include/*.h")
    add_includedirs("src/include")

target("exif4cpp_test")
    set_kind("binary")
    set_symbols("debug")
    add_deps("exif4cpp")
    add_packages("gtest")
    add_files("test/*.cpp")
    add_includedirs("src/include")
